name = "mailwebhookworker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
DOMAIN = "mailwebhookworker.USERNAME.workers.dev"
FORWARD_URL = ""
AUTH_TOKEN = ""
